const foodData = [
    {
      name: "Idli",
      offerprice: 30,
      ratings: "4.3",
      id: "1",
      title: "Idli",
      delivery: 40,
      category: 'south',
      orginalPrize: 50,
      image: "https://sukhis.com/app/uploads/2022/04/image1-6-1024x684.jpg"
    },
    {
        name: "South Indian Food Dishes",
        offerprice:25,
        ratings: "4.3",
        id: "1",
        title: "dish",
        delivery: 45,
        category: 'south',
        orginalPrize:50,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRln8uwKhXDuPGQTD3R5xQ74239CZ5mt2wOIQ&s"
      },
      {
        name: "Beyond Dosa and Vada: ",
        offerprice: 30,
        ratings: "4.3",
        id: "1",
        title: "dosa",
        delivery: 45,
        category: 'south',
        orginalPrize: 50,
        image: "https://assets.vogue.com/photos/63d169f727f1d528635b4287/16:9/w_3631,h_2042,c_limit/GettyImages-1292563627.jpg"
      },
      {
        name: "South Indian thali meal",
        offerprice: 90,
        ratings: "4.3",
        id: "1",
        title: "meal",
        delivery: 45,
        category: 'south',
        orginalPrize: 79,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3KkPnn3Af_DJQhHnMNB-NqLNc9qjUBebe0w&s"
      },
      {
        name: "Raw-Mango Rice",
        offerprice: 45,
        ratings: "4.3",
        id: "1",
        title: "rice",
        delivery: 45,
        category: 'south',
        orginalPrize: 55,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf7NJQ48KPR6uIbLz14d1SM5g1k-welGW7vA&s"
      },
      {
          name: "Curd Rice",
          offerprice: 47,
          ratings: "4.3",
          id: "1",
          title: "rice",
          delivery: 45,
          category: 'south',
          orginalPrize: 50,
          image: "https://i.ndtvimg.com/i/2016-11/curd-rice_620x350_71479882252.jpg "
        },
        {
          name: "Coconut Rice",
          offerprice: 45,
          ratings: "4.3",
          id: "1",
          title: "rice",
          delivery: 45,
          category: 'south',
          orginalPrize: 50,
          image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/05/coconut-rice-recipe-500x375.jpg"
          },
        {
          name: "Tomato Rice",
          offerprice: 50,
          ratings: "4.3",
          id: "1",
          title: "rice",
          delivery: 45,
          category: 'south',
          orginalPrize: 60,
          image: " https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0-_2WdG5MlhbZFV_itEJFJpLzXQp-G60PQLtq8bHQ3CszbO-fA8fetynxaMgQDF23ypc&usqp=CAU"
          },
        {
            name: "Brown Rice",
            offerprice: 50,
            ratings: "4.3",
            id: "1",
            title: "rice",
            delivery: 45,
            category: 'south',
            orginalPrize: 60,
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBd_gh-TZLllR-Ax8Q4mjOsAUGkvSo58mssw&s"
        },
          {
              name: "Butterfly Rice",
              offerprice: 50,
              ratings: "4.3",
              id: "1",
              title: "rice",
              delivery: 45,
              category: 'south',
              orginalPrize: 70,
              image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGdR7RmPgrK1yarfimgBL4qZfyStvjqsL0Sw&s"
            },
            {
              name: "BreakFast ",
              offerprice: 30,
              ratings: "4.3",
              id: "1",
              title: "fast",
              delivery: 45,
              category: 'south',
              orginalPrize: 40,
              image: "https://doublehorse.in/cdn/shop/articles/Steamed-Food-Recipes-for-South-Indian-Breakfast.jpg?v=1701972890"
            },
            {
              name: "South Indian meal",
              offerprice: 85,
              ratings: "4.3",
              id: "1",
              title: "meal",
              delivery: 45,
              category: 'south',
              orginalPrize: 90,
              image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeEUgQP5MvxPY3dk0LTO-oGfBxFM9Rr1Yg-w&s"
            },
            {
              name: "North Indian meal",
              offerprice: 85,
              ratings: "4.3",
              id: "1",
              title: "meal",
              delivery: 45,
              category: 'north',
              orginalPrize: 90,
              image: "https://www.chefonline.co.uk/blog/public/storage/image/post_image/post_image_21659433690.jpg"
            },
            {
              name: "North Indian Food,",
              offerprice: 80,
              ratings: "4.3",
              id: "1",
              title: "meal",
              delivery: 45,
              category: 'north',
              orginalPrize: 90,
              image:"https://5.imimg.com/data5/SELLER/Default/2023/2/QP/GG/LR/182253286/south-indian-food-500x500.jpg "
            },
            {
              name: "North Indian vegetarian food ",
              offerprice: 80,
              ratings: "4.3",
              id: "1",
              title: "meal",
              delivery: 45,
              category: 'north',
              orginalPrize: 90,
              image: "https://static.toiimg.com/photo/71219621.cms"
            },
            {
              name: "North Indian Cuisine",
              offerprice: 85,
              ratings: "4.3",
              id: "1",
              title: "meal",
              delivery: 45,
              category: 'north',
              orginalPrize: 90,
              image: "https://indianetzone.wordpress.com/wp-content/uploads/2019/02/vvvvvvvvv.jpg"
            },
            {
              name: "North Indian Food",
              offerprice: 80,
              ratings: "4.3",
              id: "1",
              title: "meal",
              delivery: 45,
              category: 'north',
              orginalPrize: 90,
              image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNVKOdqg63YbIuxuoPeM-jgmLoTZPPpeGFdw&s"
            },
            {
              name: "North Indian meal",
              offerprice: 85,
              ratings: "4.3",
              id: "1",
              title: "meal",
              delivery: 45,
              category: 'north',
              orginalPrize: 90,
              image: "https://imgmedia.lbb.in/media/2018/01/5a4ecfbc528a2648671258dd_59c232a425ba773c89b50fde_1515114428947.jpg"
            },
            {
              name: "BreakFast",
              offerprice: 85,
              ratings: "4.3",
              id: "1",
              title: "meal",
              delivery: 45,
              category: 'north',
              orginalPrize: 90,
              image: "https://cdn.tasteatlas.com//Images/Dishes/a111291d959e40789af1280bba00f5c8.jpg?w=375&h=280"
            },
            {
              name: "North Indian Chicken",
              offerprice: 85,
              ratings: "4.3",
              id: "1",
              title: "meal",
              delivery: 45,
              category: 'north',
              orginalPrize: 90,
              image: "https://data.agatetravel.com/images/photogallery/2020/fried-chicken-india.jpg"
            },
            {
              name: "North Indian BreakFast",
              offerprice: 85,
              ratings: "4.3",
              id: "1",
              title: "meal",
              delivery: 45,
              category: 'north',
              orginalPrize: 90,
              image: "https://imgmedia.lbb.in/media/2019/06/5d0b7044e1060045ad492baa_1561030724957.jpg"
            },
            {
              name: "North Indian BreakFast",
              offerprice: 85,
              ratings: "4.3",
              id: "1",
              title: "meal",
              delivery: 45,
              category: 'north',
              orginalPrize: 90,
              image: "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_auto,w_750/f_auto/North-Indian-food-phpUPkVj5"},
            {
              name: "North Indian BreakFast",
              offerprice: 82,
              ratings: "4.3",
              id: "1",
              title: "meal",
              delivery: 45,
              category: 'north',
              orginalPrize: 90,
              image: "https://imgstaticcontent.lbb.in/lbbnew/wp-content/uploads/sites/2/2016/01/mastkalandar-f.jpg"
            },
            {
              name: "North Indian Breakfast",
              offerprice: 80,
              ratings: "4.3",
              id: "1",
              title: "meal",
              delivery: 45,
              category: 'north',
              orginalPrize: 90,
              image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1mxXEeNaNkL1igY_tHSKwpEtQyZjVMWYLRg&s"
            },
            {
                name: "Kung Pao Chicken",
                offerprice: 12.99,
                ratings: "4.5",
                id: "1",
                title: "Kung Pao Chicken",
                delivery: 30,
                category: 'chinese',
                orginalPrize: 20,
                image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3b1eyjFtUOfUf0lwMxYCDJvCu5D3uEjKt8A&s"
              },
              {
                name: "Sweet and Sour Pork",
                offerprice: 10.99,
                ratings: "4.2",
                id: "2",
                title: "Sweet and Sour Pork",
                delivery: 25,
                category: "chinese",
                orginalPrize: 13.99,
                image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvAQnh_yyZtKdQYltsMO5SU1lIXM5MU0SnWQ&s"
              },
              {
                name: "Mapo Tofu",
                offerprice: 9.99,
                ratings: "4.7",
                id: "3",
                title: "Mapo Tofu",
                delivery: 20,
                category: "chinese",
                orginalPrize: 12.99,
                image: "https://twoplaidaprons.com/wp-content/uploads/2022/05/mapo-tofu-in-bowl-thumbnail.jpg"
              },
              {
                name: "Chow Mein",
                offerprice: 11.99,
                ratings: "4.4",
                id: "4",
                title: "Chow Mein",
                delivery: 15,
                category: "chinese",
                orginalPrize: 14.99,
                image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlFVtH9TvpKA-zF2uuGX4ChVVl6GZNAtV8og&s"
              },
              {
                name: "Peking Duck",
                offerprice: 25.99,
                ratings: "4.8",
                id: "5",
                title: "Peking Duck",
                delivery: 45,
                category: "chinese",
                orginalPrize: 30.99,
                image: " https://cravinghomecooked.com/wp-content/uploads/2024/02/peking-duck-1-19.jpg"
              },
              {
                name: "Dumplings",
                offerprice: 8.99,
                ratings: "4.6",
                id: "6",
                title: "Dumplings",
                delivery: 20,
                category: "chinese",
                orginalPrize: 10.99,
                image: "https://wickedwellbeing.com/wp-content/uploads/2021/11/Chicken-Dumplings.jpg"
              },
              {
                name: "Hot and Sour Soup",
                offerprice: 7.99,
                ratings: "4.3",
                id: "7",
                title: "Hot and Sour Soup",
                delivery: 15,
                category: "chinese",
                orginalPrize: 9.99,
                image: "https://www.yummytummyaarthi.com/wp-content/uploads/2022/07/hot-and-sour-chicken-soup-1.jpg"
              },
              {
                name: "Spring Rolls",
                offerprice: 5.99,
                ratings: "4.5",
                id: "8",
                title: "Spring Rolls",
                delivery: 10,
                category: "chinese",
                orginalPrize: 7.99,
                image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkQhGAMk_54CI9SjIPKPbz7gNs1fc9uWu34w&s"
              },
              {
                name: "Fried Rice",
                offerprice: 10.99,
                ratings: "4.4",
                id: "9",
                title: "Fried Rice",
                delivery: 20,
                category: "chinese",
                orginalPrize: 13.99,
                image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh9rto7rgy3nH1GxptC7Bk6eQ2s1yQO4Fa3Q&s"
              },
              {
                name: "Szechuan Beef",
                offerprice: 14.99,
                ratings: "4.6",
                id: "10",
                title: "Szechuan Beef",
                delivery: 30,
                category: "Beef",
                originalPrize: 17.99,
                image: "https://example.com/szechuan-beef.jpg"
              },
              {
                name: "Egg Foo Young",
                offerprice: 9.99,
                ratings: "4.3",
                id: "11",
                title: "Egg Foo Young",
                delivery: 25,
                category: "chinese",
                orginalPrize: 12.99,
                image: "https://mojo.generalmills.com/api/public/content/JhkT6Fxb5kmvhlkGEtWR4Q_webp_base.webp?v=2f892b45&t=e724eca7b3c24a8aaa6e089ed9e611fd"
              },
              {
                name: "Sesame Chicken",
                offerprice: 11.99,
                ratings: "4.5",
                id: "12",
                title: "Sesame Chicken",
                delivery: 30,
                category: "chinese",
                orginalPrize: 14.99,
                image: "https://twoplaidaprons.com/wp-content/uploads/2022/07/sesame-chicken-on-plate-thumbnail.jpg"
              },
              {
                name: "Beef Chow Fun",
                offerprice: 12.99,
                ratings: "4.2",
                id: "13",
                title: "Beef Chow Fun",
                delivery: 25,
                category: "chinese",
                orginalPrize: 15.99,
                image: "https://static01.nyt.com/images/2023/10/13/multimedia/as-chow-fun-htql/as-chow-fun-htql-superJumbo.jpg"},
              {
                name: "Wonton Soup",
                offerprice: 8.99,
                ratings: "4.4",
                id: "14",
                title: "Wonton Soup",
                delivery: 15,
                category: "Soup",
                originalPrize: 10.99,
                image: "https://example.com/wonton-soup.jpg"
              },
              {
                name: "Moo Shu Pork",
                offerprice: 12.99,
                ratings: "4.5",
                id: "15",
                title: "Moo Shu Pork",
                delivery: 30,
                category: "Pork",
                originalPrize: 15.99,
                image: "https://example.com/moo-shu-pork.jpg"
              }
            
            
          
];
export default foodData